name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  job-1:
    name: Publish to GitHub and PowerShell Gallery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Publish Module to PowerShell Gallery
        run: |
          Publish-Module -Path ./RancherPS -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }}
        shell: pwsh
